# Generated by Django 4.2.16 on 2024-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolomonToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('redirect_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(editable=False)),
                ('token_string', models.CharField(editable=False, max_length=128)),
                ('ip_address', models.GenericIPAddressField(editable=False, null=True)),
            ],
        ),
    ]
